Fix build: add missing #include <math.h> in cheat_phase2.c for fabs()
The build failed with error:
cheat_phase2.c:870:20: error: call to undeclared library function 'fabs'
  with type 'double (double)'; ISO C99 and later do not support
  implicit function declarations [-Wimplicit-function-declaration]

fabs() requires <math.h> to be included.